[tools]
amp = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
aws-nuke = "latest"
cmake = "latest"
gcloud = "latest"
gemini = "latest"
gh = "latest"
go = "latest"
jq = "latest"
make = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
"npm:turbo" = "latest"
opencode = "latest"
pnpm = "latest"
python = "latest"
rust = "stable"
terraform = "latest"
uv = "latest"
yq = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
PROJECT_NAME = "{{ config_root | basename }}"
BIN_PATH = "{{ config_root }}/node_modules/.bin"
UV_VENV_SEED = 1

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
experimental = true
