[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
cmake = "latest"
gcloud = "latest"
go = "latest"
make = "latest"
node = "latest"
"npm:turbo" = "latest"
rust = "stable"
terraform = "latest"
uv = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Set up the path for node module binaries
BIN_PATH = "{{ config_root }}/node_modules/.bin"

[tasks.build]
run = 'echo "running build tasks"'

[tasks.jupyter]
description = "Start global JupyterLab server"
run = """
cd ~/jupyter
source .venv/bin/activate
jupyter lab --no-browser --ip=127.0.0.1
"""

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
experimental = false
